version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - app
      - redis
    networks:
      - default
      - frontend
    ports:
      - "8080:80"
  app:
    build: ./app
    environment:
      - FLASK_ENV
    networks:
      - frontend
      - backend
    volumes:
      - ./app:/code
  redis:
    image: "redis:alpine"
    networks:
      - backend
networks:
  frontend:
  backend:
